version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      GitHub_Actions:
        patterns:
          - "*"  # Group all Actions updates into a single larger pull request
    labels: ["dependencies"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["dependencies"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    labels: ["dependencies"]
    versioning-strategy: increase
    schedule:
      interval: "monthly"
